import asyncio
import json

from langchain_ollama import ChatOllama

from mcp.client.stdio import stdio_client, StdioServerParameters
from mcp import ClientSession


# ============================================================
# CONFIG
# ============================================================

MODEL_NAME = "qwen3:1.7b"

# Maximum number of times the agent can call tools
# for one user request.
MAX_TOOL_ROUNDS = 2

# Keep only recent conversation items.
MAX_MEMORY_ITEMS = 6

# Prevent large tool results from filling the prompt.
MAX_TOOL_OUTPUT_CHARS = 4000


# ============================================================
# LLM
# ============================================================

llm = ChatOllama(
    model=MODEL_NAME,
    temperature=0
)


# ============================================================
# CONVERSATION MEMORY
# ============================================================

memory = []


def add_memory(text):
    """
    Store only recent conversation information.

    Large memory makes the prompt larger,
    which makes a small local LLM slower.
    """

    memory.append(text)

    if len(memory) > MAX_MEMORY_ITEMS:
        del memory[:-MAX_MEMORY_ITEMS]


def get_memory_text():
    """
    Convert recent memory into a small prompt section.
    """

    if not memory:
        return "No previous context."

    return "\n".join(memory)


# ============================================================
# COMPACT OUTPUT
# ============================================================

def compact_text(text, limit=MAX_TOOL_OUTPUT_CHARS):
    """
    Keep tool results small before sending them
    back to the LLM.
    """

    if not text:
        return "No output."

    text = str(text)

    if len(text) <= limit:
        return text

    return (
        text[:limit]
        + "\n\n...[tool output truncated]"
    )


# ============================================================
# MCP TOOL FORMAT
# ============================================================

def convert_mcp_tools(mcp_tools):
    """
    Convert MCP tools into the format expected
    by LangChain/Ollama tool calling.
    """

    return [
        {
            "type": "function",
            "function": {
                "name": tool.name,
                "description": tool.description or "",
                "parameters": tool.inputSchema
            }
        }
        for tool in mcp_tools
    ]


def get_tool_names(tool_list):
    """
    Create a set of valid MCP tool names.

    Used to prevent accidental calls to unknown tools.
    """

    return {
        tool["function"]["name"]
        for tool in tool_list
    }


# ============================================================
# EXTRACT TOOL CALLS
# ============================================================

def extract_tool_calls(response):
    """
    Get tool calls generated by the LLM.
    """

    calls = getattr(response, "tool_calls", None)

    if calls:
        return calls

    return []


# ============================================================
# EXTRACT TOOL NAME + ARGUMENTS
# ============================================================

def extract_call_data(call):
    """
    Support both common LangChain tool-call formats.
    """

    if not isinstance(call, dict):
        return None, {}

    # --------------------------------------------------------
    # Normal LangChain format
    # --------------------------------------------------------

    name = call.get("name")
    args = call.get("args")

    # --------------------------------------------------------
    # Nested function format
    # --------------------------------------------------------

    if not name:

        function_data = call.get(
            "function",
            {}
        )

        name = function_data.get("name")

        args = function_data.get(
            "arguments",
            {}
        )

    # --------------------------------------------------------
    # Arguments may arrive as JSON string
    # --------------------------------------------------------

    if isinstance(args, str):

        try:
            args = json.loads(args)

        except json.JSONDecodeError:

            args = {}

    if args is None:
        args = {}

    return name, args


# ============================================================
# EXTRACT MCP RESULT
# ============================================================

def extract_tool_output(result):
    """
    Extract text returned by the MCP tool.
    """

    output_parts = []

    for item in result.content:

        if hasattr(item, "text") and item.text:

            output_parts.append(
                item.text
            )

    if not output_parts:
        return "Tool returned no text output."

    return "\n".join(output_parts)


# ============================================================
# BUILD AGENT PROMPT
# ============================================================

def build_agent_prompt(
    user_input,
    task_context
):
    """
    Build a compact prompt for Qwen.

    Important:
    - Conversation memory = previous requests/answers
    - Task context = current tool results
    """

    return f"""
You are a small local AI agent.

Your job is to understand the user's request
and use MCP tools when necessary.

IMPORTANT RULES:

1. Use a tool only when it is actually needed.
2. Let Python perform calculations and heavy data processing.
3. Do not manually perform heavy calculations.
4. Use the tool result instead of repeating the work.
5. If the task is complete, answer the user directly.
6. If another tool is absolutely necessary, call it.
7. Keep the final answer concise.
8. Do not reveal internal reasoning.

Recent conversation:
{get_memory_text()}

Current user request:
{user_input}

Current task/tool context:
{task_context if task_context else "No tool has been used yet."}
"""


# ============================================================
# EXECUTE ONE TOOL CALL
# ============================================================

async def execute_tool(
    session,
    name,
    args,
    valid_tools
):
    """
    Execute one MCP tool and return compact output.
    """

    # --------------------------------------------------------
    # Validate tool name
    # --------------------------------------------------------

    if name not in valid_tools:

        return (
            f"ERROR: Unknown tool '{name}'. "
            f"Available tools: "
            f"{', '.join(sorted(valid_tools))}"
        )

    try:

        print(
            f"🔧 Tool: {name}"
        )

        result = await session.call_tool(
            name,
            args
        )

        output = extract_tool_output(
            result
        )

        return compact_text(
            output
        )

    except Exception as e:

        return (
            f"ERROR while running tool "
            f"'{name}': {str(e)}"
        )


# ============================================================
# MAIN AGENT
# ============================================================

async def run():

    print(
        "\n🔥 FAST MCP LOCAL AGENT STARTED"
    )

    print(
        f"🤖 Model: {MODEL_NAME}"
    )

    print(
        "💡 LLM decides, MCP/Python does the work.\n"
    )

    # ========================================================
    # MCP SERVER
    # ========================================================

    server = StdioServerParameters(
        command="python",
        args=["mcp_server.py"]
    )

    async with stdio_client(server) as (
        read,
        write
    ):

        async with ClientSession(
            read,
            write
        ) as session:

            # =================================================
            # INITIALIZE MCP
            # =================================================

            await session.initialize()

            # =================================================
            # LOAD TOOLS ONLY ONCE
            # =================================================

            mcp_response = (
                await session.list_tools()
            )

            tool_list = convert_mcp_tools(
                mcp_response.tools
            )

            valid_tools = get_tool_names(
                tool_list
            )

            print(
                f"🛠️ MCP tools loaded: "
                f"{len(tool_list)}"
            )

            print(
                f"🧰 Tools: "
                f"{', '.join(sorted(valid_tools))}"
            )

            # =================================================
            # USER LOOP
            # =================================================

            while True:

                try:

                    user_input = input(
                        "\nYOU: "
                    ).strip()

                except (
                    KeyboardInterrupt,
                    EOFError
                ):

                    print(
                        "\n\n👋 Exiting..."
                    )

                    break

                # =================================================
                # EXIT
                # =================================================

                if user_input.lower() in {
                    "exit",
                    "quit"
                }:

                    print(
                        "\n👋 Goodbye!"
                    )

                    break

                if not user_input:
                    continue

                # =================================================
                # CURRENT TASK CONTEXT
                # =================================================

                task_context = ""

                # =================================================
                # STORE USER REQUEST
                # =================================================

                add_memory(
                    f"User: {user_input}"
                )

                # =================================================
                # AGENT LOOP
                # =================================================

                tool_round = 0

                while True:

                    # ------------------------------------------------
                    # BUILD PROMPT
                    # ------------------------------------------------

                    prompt = build_agent_prompt(
                        user_input,
                        task_context
                    )

                    print(
                        "\n🧠 Deciding...",
                        end="",
                        flush=True
                    )

                    # ------------------------------------------------
                    # ASK LLM
                    # ------------------------------------------------

                    response = llm.invoke(
                        prompt,
                        tools=tool_list
                    )

                    # ------------------------------------------------
                    # CHECK TOOL CALLS
                    # ------------------------------------------------

                    tool_calls = extract_tool_calls(
                        response
                    )

                    # =================================================
                    # NO TOOL REQUIRED
                    # =================================================

                    if not tool_calls:

                        print(
                            "\n\n🤖 Answer:\n"
                        )

                        if hasattr(
                            response,
                            "content"
                        ):

                            answer = response.content

                        else:

                            answer = str(
                                response
                            )

                        print(
                            answer
                        )

                        # --------------------------------------------
                        # Save final answer to memory
                        # --------------------------------------------

                        add_memory(
                            f"Assistant: {answer}"
                        )

                        break

                    # =================================================
                    # TOOL LIMIT CHECK
                    # =================================================

                    if tool_round >= MAX_TOOL_ROUNDS:

                        print(
                            "\n\n⚠️ Maximum tool "
                            "rounds reached."
                        )

                        print(
                            "The agent stopped to "
                            "avoid excessive LLM/tool calls."
                        )

                        break

                    tool_round += 1

                    print(
                        f"\n\n⚙️ Tool round "
                        f"{tool_round}/"
                        f"{MAX_TOOL_ROUNDS}"
                    )

                    # =================================================
                    # EXECUTE ALL TOOL CALLS
                    # =================================================

                    round_results = []

                    for call in tool_calls:

                        name, args = (
                            extract_call_data(
                                call
                            )
                        )

                        if not name:

                            print(
                                "❌ Invalid tool call."
                            )

                            round_results.append(
                                "ERROR: Invalid tool call."
                            )

                            continue

                        print(
                            f"📡 Calling {name}..."
                        )

                        output = await execute_tool(
                            session,
                            name,
                            args,
                            valid_tools
                        )

                        print(
                            "\n📄 Tool result:"
                        )

                        print(
                            output
                        )

                        round_results.append(
                            f"Tool: {name}\n"
                            f"Result:\n{output}"
                        )

                    # =================================================
                    # UPDATE CURRENT TASK CONTEXT
                    # =================================================

                    task_context = (
                        "\n\n".join(
                            round_results
                        )
                    )

                    # ------------------------------------------------
                    # IMPORTANT
                    # ------------------------------------------------
                    #
                    # We DO NOT make a separate follow-up LLM call.
                    #
                    # The while loop simply starts again.
                    #
                    # Therefore:
                    #
                    # LLM
                    #   ↓
                    # Tool
                    #   ↓
                    # Result
                    #   ↓
                    # LLM
                    #
                    # ------------------------------------------------

                print(
                    "\n" + "=" * 60
                )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    asyncio.run(
        run()
    )